name: Run Class Availability Scraper

on:
  schedule:
    - cron: '*/47 * * * *'
  workflow_dispatch:

jobs:
  scrape_and_alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Application Requirements
      run: |
        pip install --no-cache-dir -r requirements.txt

    - name: Configure Playwright Browsers
      run: |
        playwright install --with-deps chromium

    - name: Run Class Scraper Script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        RECIEVER_PHONE: ${{ secrets.RECIEVER_PHONE }}
        PYTHONUNBUFFERED: "1"
      run: python main.py
